Repository secureCodeBox/engine, pull requests merged in 2019-08, with the labels that each got.

#87 Feature/wordpress scanner
  Dockerfile
  scb-engine/pom.xml
  scb-scanprocesses/pom.xml
  scb-scanprocesses/wordpress-process/pom.xml
  scb-scanprocesses/wordpress-process/src/main/java/io/securecodebox/scanprocess/ProcessInitConfiguration.java
  scb-scanprocesses/wordpress-process/src/main/resources/META-INF/processes.xml
  scb-scanprocesses/wordpress-process/src/main/resources/bpmn/wordpress_process.bpmn
  scb-scanprocesses/wordpress-process/src/main/resources/forms/wordpress/approve-results.html
  scb-scanprocesses/wordpress-process/src/main/resources/forms/wordpress/configure-target.html
  scb-scanprocesses/wordpress-process/src/test/java/io/securecodebox/scanprocess/test/WordpressProcessTest.java
  scb-scanprocesses/wordpress-process/src/test/resources/camunda.cfg.xml
  scb-scanprocesses/wordpress-process/src/test/resources/logback-test.xml
Labels: enhancement

#95 Add missing permissions to ci group
  scb-engine/src/main/java/io/securecodebox/engine/helper/DefaultGroupConfiguration.java
Labels: bug

#100 Ensure that Groups are always Created before the Users
  scb-engine/src/main/java/io/securecodebox/engine/helper/DefaultGroupConfiguration.java
  scb-engine/src/main/java/io/securecodebox/engine/helper/DefaultUserConfiguration.java
Labels: bug

#101 Reduce Database Write Clutter in Nmap Process
  scb-engine/src/main/java/io/securecodebox/engine/execution/DefaultScanProcessExecution.java
  scb-scanprocesses/combined-amass-nmap-process/src/main/java/io/securecodebox/scanprocesses/amassnmap/FilterHttpSecurityHeaders.java
  scb-sdk/src/main/java/io/securecodebox/model/execution/ScanProcessExecution.java
Labels: bug

#103 Replace develop docker tag with unstable tag
  .travis/deployDockerHub.sh
Labels: maintenance
